version: '3'
services:
#  db:
#    image: postgres
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
  web:
    container_name: "ruby_blog_demo"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/container_shared/post_board/public/system:/app/public/system
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - DOCKERIZED=true
      - RAILS_SERVE_STATIC_FILES=true
    network_mode: host
#      DATABASE_URL: postgres://postgres@db
#    depends_on:
#      - db