class Services::DayKarmaEvent::EventTypes

  WHEN_THIS_USERS_POST_LIKED_OR_DISLIKED = 1
  WHEN_THIS_USERS_POST_LIKE_CANCELLED = 2
  WHEN_THIS_USERS_POST_DISLIKE_CANCELLED = 3

  WHEN_POST_LIKED_OR_DISLIKED = 4
  WHEN_FRESH_POST_LIKED_OR_DISLIKED = 5
  WHEN_POST_LIKE_OR_DISLIKE_CANCELLED = 6



  WHEN_USER_CREATED_POST = 7



  WHEN_THIS_USERS_DISCUSSION_MESSAGE_LIKED_OR_DISLIKED = 8
  WHEN_THIS_USERS_DISCUSSION_MESSAGE_LIKE_CANCELLED = 9
  WHEN_THIS_USERS_DISCUSSION_MESSAGE_DISLIKE_CANCELLED = 10

  WHEN_DISCUSSION_MESSAGE_LIKED_OR_DISLIKED = 11
  WHEN_DISCUSSION_MESSAGE_LIKE_OR_DISLIKE_CANCELLED = 12


  THIS_USERS_COMMENT_KARMA_CHANGED = 8
  THIS_USERS_POST_WAS_COMMENTED = 9
  THIS_USERS_POST_IS_IN_HOT = 10
  USER_REGISTERED = 11
  USER_COMMENTED = 12
  THIS_USERS_COMMENT_LIKE_CANCELLED = 13
  THIS_USERS_COMMENT_DISLIKE_CANCELLED = 14


  ALLOWED_EVENT_TYPES = [

  ]

end
