class KarmaManager

  FOR_COMMENT_CREATION = 50

  WHEN_SUBSCRIBED_TO_USER = 100

  WHEN_UNSUBSCRIBED_FROM_USER = -100

  WHEN_SUBSCRIBED_TO_THIS_USER = 500

  WHEN_UNSUBSCRIBED_FROM_THIS_USER = -500

  WHEN_LIKED_OR_DISLIKED_THIS_USERS_POST = 50

  COMMENT_UP_OR_DOWN_VOTED = 10

  USERS_COMMENT_UP_OR_DOWN_VOTED = 20

end